services:
  csvserver:
    container_name: csvserver
    environment:
      - CSVSERVER_BORDER=Orange
    image: infracloudio/csvserver:latest
    hostname: csvserver
    ports:
      - "9393:9300"
    restart: always
    volumes:
      - "./inputFile:/csvserver/inputdata:ro,z"
  prometheus:
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    image: prom/prometheus:v2.22.0
    hostname: prometheus
    ports:
      - "9090:9090"
    # restart: on-failure
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro,z"
